image: node:latest

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - tests

setup:
  stage: setup
  artifacts:
    expire_in: 10 minutes
    paths:
      - node_modules/
  script:
    - npm i

tests:
  stage: tests
  artifacts:
    expire_in: 10 minutes
    paths:
      - node_modules/
  script:
    - npm test
