language: node_js

node_js:
  - "10"

addons:
  sonarcloud:
    token:
      secure: "a9d62f889c262b5909478eeb0a596b30585d57fa"

install:
  - npm i

jobs:
  include:
    - stage: Audit NPM Packages
      script: npm audit
    - stage: Test Coverage
      script: npm run coverage
    - stage: Run Code Analysis
      script: sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
