language: node_js

node_js:
  - "10"

addons:
  sonarcloud:
    token:
      secure: "a9d62f889c262b5909478eeb0a596b30585d57fa"

install:
  - npm i

script:
  - npm run coverage
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
