language: node_js

node_js:
  - "10"

addons:
  sonarcloud:
    token:
      secure: "a9d62f889c262b5909478eeb0a596b30585d57fa"

install:
  - npm i

stages:
  - audit
  - lint
  - test
  - sonar

jobs:
  include:
    - stage: audit
      name: "NPM Audit"
      script:
        - npm audit
    - stage: lint
      name: "Code Linting"
      script:
        - npm run lint
    - stage: test
      name: "Code Testing"
      script:
        - npm run coverage
    - stage: sonar
      name: "Code Analysis"
      script:
        - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
    - 'node_modules'
    - 'coverage'
